# Site settings
name: DoubleRay`Blog
email: doubleray.wang@gmail.com
author: DoubleRay Wang
url: http://doubleray.win
resume_site: /resume
github: https://github.com/DoubleRayWang/
baseurl: ""
description: 看护好自己曾经的激情与理想，在这个怀疑的年代，依然需要信仰。
motto: 不懂的知识就努力去补充，这才是成长之道！
banner: 学而不思则罔，思而不学则殆。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->'
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: DoubleRayWang
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : doubleray